name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: 'Hello'
        required: true
        descriottion: A greeting to include in the output
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{ inputs.greeting }}"